# Generated by Django 4.2.6 on 2023-10-29 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarData1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=150)),
                ('c_company', models.CharField(max_length=150)),
                ('c_model', models.CharField(max_length=150)),
                ('c_price', models.BigIntegerField()),
                ('c_fueltype', models.CharField(max_length=150)),
            ],
        ),
    ]
